//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTable
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int EventType { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string Description { get; set; }
        public System.DateTime EventDateTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual SupportTask SupportTask { get; set; }
    }
}
