//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchArea
    {
        public int UserId { get; set; }
        public Nullable<int> City1 { get; set; }
        public Nullable<int> City2 { get; set; }
        public Nullable<int> City3 { get; set; }
        public Nullable<int> City4 { get; set; }
    
        public virtual User User { get; set; }
        public virtual City City { get; set; }
        public virtual City City5 { get; set; }
        public virtual City City6 { get; set; }
        public virtual City City7 { get; set; }
    }
}
