//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopperAddress
    {
        public int UserId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressLine4 { get; set; }
        public int Locality { get; set; }
        public int Region { get; set; }
        public string Postcode { get; set; }
        public int Country { get; set; }
    
        public virtual User User { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual State State { get; set; }
    }
}
