//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportTask
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public int RaisedBy { get; set; }
        public Nullable<int> ClosedBy { get; set; }
        public int Status { get; set; }
        public System.DateTime DateRaised { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public int severity { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
