//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1
{
    using System;
    using System.Collections.Generic;
    
    public partial class uk_towns
    {
        public int id { get; set; }
        public string name { get; set; }
        public string county { get; set; }
        public string country { get; set; }
        public string grid_reference { get; set; }
        public Nullable<int> easting { get; set; }
        public Nullable<int> northing { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<int> elevation { get; set; }
        public string postcode_sector { get; set; }
        public string local_government_area { get; set; }
        public string nuts_region { get; set; }
        public string type { get; set; }
    }
}
