//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.SupportTasks = new HashSet<SupportTask>();
            this.SupportTasks1 = new HashSet<SupportTask>();
            this.SupportTasks2 = new HashSet<SupportTask>();
        }
    
        public int Id { get; set; }
        public string AspNetUsersId { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public bool KYCVerified { get; set; }
        public string RefId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SearchArea SearchArea { get; set; }
        public virtual ShopperAddress ShopperAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportTask> SupportTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportTask> SupportTasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportTask> SupportTasks2 { get; set; }
        public virtual VolunteerAddress VolunteerAddress { get; set; }
    }
}
